apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app
  namespace: canary-k8s-operator-system
spec:
  replicas: 10
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.21.1
        ports:
        - containerPort: 80
